[package]
name = "xterm_rs"
version = "0.1.0"
authors = ["Jay Kint <jkint@icosahedron.org>"]
edition = "2018"

[lib]
crate-type = ['staticlib']

[dependencies]
readonly = "0.1"
lazy_static = "1.4.0"
log = "^0.4.8"
